<?php
/**
 * Customizer field registry (defaults match the approved HTML).
 *
 * @package AarohCare
 */

if (!defined('ABSPATH')) {
    exit;
}

function aaroh_customizer_sections()
{
    return [
        'aaroh_seo'            => 'SEO and identity',
        'aaroh_header'         => 'Header brand',
        'aaroh_nav'            => 'Navigation',
        'aaroh_hero'           => 'Hero',
        'aaroh_hero_showcase'  => 'Hero showcase panel',
        'aaroh_consult_topics' => 'Consultation topics bar',
        'aaroh_articles_carousel' => 'Home articles carousel',
        'aaroh_services_head'  => 'Services heading',
        'aaroh_benefits_head'  => 'Why Us heading',
        'aaroh_gallery_head'   => 'Gallery heading',
        'aaroh_appointment'    => 'Appointment copy',
        'aaroh_form'           => 'Appointment form',
        'aaroh_faq_head'       => 'FAQ heading',
        'aaroh_articles_head'  => 'Articles page heading',
        'aaroh_footer'         => 'Footer',
    ];
}

function aaroh_fields()
{
    return [
        'seo_title' => [
            'section' => 'aaroh_seo',
            'label'   => 'SEO title',
            'type'    => 'text',
            'default' => 'AAROH CARE - HOMOEOPATHY | Online Homoeopathic Consultations',
        ],
        'seo_description' => [
            'section' => 'aaroh_seo',
            'label'   => 'Meta description',
            'type'    => 'textarea',
            'default' => 'Welcome to AAROH CARE - HOMOEOPATHY. Book online homoeopathic consultations for hormonal disorders, diabetes, obesity, thyroid disorders, PCOS/PCOD, skin and hair concerns, allergies, digestive disorders, migraine, lifestyle disorders, and general wellness.',
        ],
        'seo_keywords' => [
            'section' => 'aaroh_seo',
            'label'   => 'Meta keywords',
            'type'    => 'textarea',
            'default' => 'AAROH CARE HOMOEOPATHY, online homoeopathic consultation, Dr. Ritika Trivedi, hormonal disorders, diabetes, PCOS, thyroid disorders, skin and hair, digestive disorders, migraine, holistic wellbeing',
        ],
        'seo_author' => [
            'section' => 'aaroh_seo',
            'label'   => 'Author',
            'type'    => 'text',
            'default' => 'Aaroh Care Homoeopathy',
        ],
        'og_title' => [
            'section' => 'aaroh_seo',
            'label'   => 'Open Graph title',
            'type'    => 'text',
            'default' => 'AAROH CARE - HOMOEOPATHY | Online Homoeopathic Consultations',
        ],
        'og_description' => [
            'section' => 'aaroh_seo',
            'label'   => 'Open Graph description',
            'type'    => 'textarea',
            'default' => 'Holistic, compassionate, and individualized homoeopathic care with online consultations by prior appointment.',
        ],
        'twitter_title' => [
            'section' => 'aaroh_seo',
            'label'   => 'Twitter title',
            'type'    => 'text',
            'default' => 'AAROH CARE - HOMOEOPATHY',
        ],
        'twitter_description' => [
            'section' => 'aaroh_seo',
            'label'   => 'Twitter description',
            'type'    => 'textarea',
            'default' => 'Online homoeopathic consultations by prior appointment with Dr. Ritika Trivedi (BHMS).',
        ],
        'jsonld_name' => [
            'section' => 'aaroh_seo',
            'label'   => 'Clinic name (JSON-LD)',
            'type'    => 'text',
            'default' => 'Aaroh Care Homoeopathy',
        ],
        'jsonld_description' => [
            'section' => 'aaroh_seo',
            'label'   => 'Clinic description (JSON-LD)',
            'type'    => 'textarea',
            'default' => 'Holistic, compassionate, and individualized homoeopathic care with online consultations by prior appointment.',
        ],
        'jsonld_hours' => [
            'section' => 'aaroh_seo',
            'label'   => 'Opening hours (schema.org)',
            'type'    => 'text',
            'default' => 'Mo-Sa 16:00-19:00',
        ],
        'jsonld_specialty' => [
            'section' => 'aaroh_seo',
            'label'   => 'Medical specialty',
            'type'    => 'text',
            'default' => 'Homeopathic',
        ],
        'physician_name' => [
            'section' => 'aaroh_seo',
            'label'   => 'Physician name',
            'type'    => 'text',
            'default' => 'Dr. Ritika Trivedi',
        ],
        'physician_suffix' => [
            'section' => 'aaroh_seo',
            'label'   => 'Physician suffix',
            'type'    => 'text',
            'default' => 'BHMS',
        ],
        'clinic_email' => [
            'section' => 'aaroh_seo',
            'label'   => 'Clinic email (appointment notifications)',
            'type'    => 'email',
            'default' => '',
        ],
        'brand_name' => [
            'section' => 'aaroh_header',
            'label'   => 'Brand name',
            'type'    => 'text',
            'default' => 'Aaroh Care',
        ],
        'brand_tagline' => [
            'section' => 'aaroh_header',
            'label'   => 'Brand tagline',
            'type'    => 'text',
            'default' => 'Natural Healing. Holistic Wellbeing.',
        ],
        'logo_alt' => [
            'section' => 'aaroh_header',
            'label'   => 'Logo alt text',
            'type'    => 'text',
            'default' => 'Aaroh Care logo',
        ],
        'nav_services' => [
            'section' => 'aaroh_nav',
            'label'   => 'Services link',
            'type'    => 'text',
            'default' => 'Services',
        ],
        'nav_benefits' => [
            'section' => 'aaroh_nav',
            'label'   => 'Why Us link',
            'type'    => 'text',
            'default' => 'Why Us',
        ],
        'nav_gallery' => [
            'section' => 'aaroh_nav',
            'label'   => 'Gallery link',
            'type'    => 'text',
            'default' => 'Gallery',
        ],
        'nav_faq' => [
            'section' => 'aaroh_nav',
            'label'   => 'FAQ link',
            'type'    => 'text',
            'default' => 'FAQ',
        ],
        'nav_articles' => [
            'section' => 'aaroh_nav',
            'label'   => 'Articles link',
            'type'    => 'text',
            'default' => 'Articles',
        ],
        'nav_cta' => [
            'section' => 'aaroh_nav',
            'label'   => 'Book Appointment button',
            'type'    => 'text',
            'default' => 'Book Appointment',
        ],
        'hero_eyebrow' => [
            'section' => 'aaroh_hero',
            'label'   => 'Eyebrow',
            'type'    => 'text',
            'default' => 'Welcome to AAROH CARE - HOMOEOPATHY',
        ],
        'hero_title' => [
            'section' => 'aaroh_hero',
            'label'   => 'Headline',
            'type'    => 'textarea',
            'default' => 'Every healing journey begins with hope.',
        ],
        'hero_lead' => [
            'section' => 'aaroh_hero',
            'label'   => 'Lead paragraph',
            'type'    => 'textarea',
            'default' => 'AAROH CARE - HOMOEOPATHY is a space dedicated to holistic, compassionate, and individualized homoeopathic care. The goal is to understand you as a whole person, not just your illness, and support your journey toward better health and well-being.',
        ],
        'hero_cta_primary' => [
            'section' => 'aaroh_hero',
            'label'   => 'Primary button',
            'type'    => 'text',
            'default' => 'Book Online Consultation',
        ],
        'hero_cta_secondary' => [
            'section' => 'aaroh_hero',
            'label'   => 'Secondary button',
            'type'    => 'text',
            'default' => 'View Consultation Areas',
        ],
        'metric_1_value' => [
            'section' => 'aaroh_hero',
            'label'   => 'Metric 1 value',
            'type'    => 'text',
            'default' => '12+',
        ],
        'metric_1_label' => [
            'section' => 'aaroh_hero',
            'label'   => 'Metric 1 label',
            'type'    => 'text',
            'default' => 'Consultation areas',
        ],
        'metric_2_value' => [
            'section' => 'aaroh_hero',
            'label'   => 'Metric 2 value',
            'type'    => 'text',
            'default' => '6 Days',
        ],
        'metric_2_label' => [
            'section' => 'aaroh_hero',
            'label'   => 'Metric 2 label',
            'type'    => 'text',
            'default' => 'Mon-Sat appointments',
        ],
        'metric_3_value' => [
            'section' => 'aaroh_hero',
            'label'   => 'Metric 3 value',
            'type'    => 'text',
            'default' => '4-7 PM',
        ],
        'metric_3_label' => [
            'section' => 'aaroh_hero',
            'label'   => 'Metric 3 label',
            'type'    => 'text',
            'default' => 'Consultation hours',
        ],
        'showcase_label' => [
            'section' => 'aaroh_hero_showcase',
            'label'   => 'Panel label',
            'type'    => 'text',
            'default' => 'Aaroh Care Homoeopathy',
        ],
        'showcase_title' => [
            'section' => 'aaroh_hero_showcase',
            'label'   => 'Panel title',
            'type'    => 'textarea',
            'default' => 'Online homoeopathic consultations available by prior appointment.',
        ],
        'showcase_card_1_label' => [
            'section' => 'aaroh_hero_showcase',
            'label'   => 'Card 1 label',
            'type'    => 'text',
            'default' => 'Consultation Areas',
        ],
        'showcase_card_1_body' => [
            'section' => 'aaroh_hero_showcase',
            'label'   => 'Card 1 list (one item per line)',
            'type'    => 'textarea',
            'default' => "Hormonal disorders, thyroid disorders, and PCOS/PCOD\nDiabetes, obesity, and lifestyle-related concerns\nSkin, hair, allergy, and respiratory support\nDigestive, migraine, acute, and chronic illness care",
        ],
        'showcase_card_2_label' => [
            'section' => 'aaroh_hero_showcase',
            'label'   => 'Card 2 label',
            'type'    => 'text',
            'default' => 'Consultation Hours',
        ],
        'showcase_card_2_body' => [
            'section' => 'aaroh_hero_showcase',
            'label'   => 'Card 2 list (one item per line)',
            'type'    => 'textarea',
            'default' => "Online consultations by prior appointment\nMonday to Saturday availability\n4 PM to 7 PM consultation window",
        ],
        'showcase_card_3_label' => [
            'section' => 'aaroh_hero_showcase',
            'label'   => 'Card 3 label',
            'type'    => 'text',
            'default' => 'Founder',
        ],
        'showcase_card_3_title' => [
            'section' => 'aaroh_hero_showcase',
            'label'   => 'Card 3 title',
            'type'    => 'text',
            'default' => 'Dr. Ritika Trivedi, BHMS',
        ],
        'showcase_card_3_body' => [
            'section' => 'aaroh_hero_showcase',
            'label'   => 'Card 3 body',
            'type'    => 'textarea',
            'default' => 'BHMS. Natural Healing. Holistic Wellbeing. Care is centered on understanding the person as a whole and guiding steady recovery with compassion.',
        ],
        'consult_topics_title' => [
            'section' => 'aaroh_consult_topics',
            'label'   => 'Heading',
            'type'    => 'text',
            'default' => 'Online Consultations Available For',
        ],
        'consult_topics_items' => [
            'section' => 'aaroh_consult_topics',
            'label'   => 'Topics (one per line)',
            'type'    => 'textarea',
            'default' => "Hormonal Disorders\nDiabetes\nObesity\nThyroid Disorders\nPCOS/PCOD\nWomen's Health\nSkin & Hair\nAllergies\nDigestive Disorders\nMigraine\nAcute & Chronic Illnesses\nGeneral Wellness",
        ],
        'articles_carousel_eyebrow' => [
            'section' => 'aaroh_articles_carousel',
            'label'   => 'Eyebrow',
            'type'    => 'text',
            'default' => 'Journal',
        ],
        'articles_carousel_title' => [
            'section' => 'aaroh_articles_carousel',
            'label'   => 'Title',
            'type'    => 'text',
            'default' => 'Recent articles from Aaroh Care',
        ],
        'articles_carousel_link' => [
            'section' => 'aaroh_articles_carousel',
            'label'   => 'View all label',
            'type'    => 'text',
            'default' => 'View all articles',
        ],
        'services_eyebrow' => [
            'section' => 'aaroh_services_head',
            'label'   => 'Eyebrow',
            'type'    => 'text',
            'default' => 'Consultation Areas',
        ],
        'services_title' => [
            'section' => 'aaroh_services_head',
            'label'   => 'Title',
            'type'    => 'textarea',
            'default' => 'Online homoeopathic consultations available for a wide range of health concerns.',
        ],
        'services_intro' => [
            'section' => 'aaroh_services_head',
            'label'   => 'Intro',
            'type'    => 'textarea',
            'default' => 'Each area reflects the real consultation focus of AAROH CARE - HOMOEOPATHY and helps patients quickly understand whether the clinic is right for their needs.',
        ],
        'benefits_eyebrow' => [
            'section' => 'aaroh_benefits_head',
            'label'   => 'Eyebrow',
            'type'    => 'text',
            'default' => 'Why Aaroh Care',
        ],
        'benefits_title' => [
            'section' => 'aaroh_benefits_head',
            'label'   => 'Title',
            'type'    => 'textarea',
            'default' => 'Care that is holistic, compassionate, and individualized.',
        ],
        'benefits_intro' => [
            'section' => 'aaroh_benefits_head',
            'label'   => 'Intro',
            'type'    => 'textarea',
            'default' => 'The focus is to understand each patient as a whole person, not just a diagnosis, and support a meaningful path toward better health and wellbeing.',
        ],
        'gallery_eyebrow' => [
            'section' => 'aaroh_gallery_head',
            'label'   => 'Eyebrow',
            'type'    => 'text',
            'default' => 'Care highlights',
        ],
        'gallery_title' => [
            'section' => 'aaroh_gallery_head',
            'label'   => 'Title',
            'type'    => 'textarea',
            'default' => 'A closer look at the consultation focus of Aaroh Care Homoeopathy.',
        ],
        'gallery_intro' => [
            'section' => 'aaroh_gallery_head',
            'label'   => 'Intro',
            'type'    => 'textarea',
            'default' => 'These highlights help patients quickly identify common health areas supported through online consultation.',
        ],
        'appt_eyebrow' => [
            'section' => 'aaroh_appointment',
            'label'   => 'Eyebrow',
            'type'    => 'text',
            'default' => 'Online appointment',
        ],
        'appt_title' => [
            'section' => 'aaroh_appointment',
            'label'   => 'Title',
            'type'    => 'textarea',
            'default' => 'Collect patient details before the visit.',
        ],
        'appt_intro' => [
            'section' => 'aaroh_appointment',
            'label'   => 'Intro',
            'type'    => 'textarea',
            'default' => 'Patients can share their details, health concern, and preferred consultation schedule before an online consultation with Aaroh Care.',
        ],
        'appt_note_title' => [
            'section' => 'aaroh_appointment',
            'label'   => 'Note heading',
            'type'    => 'text',
            'default' => 'Consultation details',
        ],
        'appt_note_items' => [
            'section' => 'aaroh_appointment',
            'label'   => 'Note list (one item per line)',
            'type'    => 'textarea',
            'default' => "Online consultations by prior appointment\nConsultation hours: Mon-Sat | 4 PM-7 PM\nFull name and contact number\nEmail address\nHealth issue or symptoms\nPreferred date and time slot within clinic hours",
        ],
        'appt_submit' => [
            'section' => 'aaroh_appointment',
            'label'   => 'Submit button',
            'type'    => 'text',
            'default' => 'Request Appointment',
        ],
        'appt_success' => [
            'section' => 'aaroh_appointment',
            'label'   => 'Success message ({name}, {date}, {time})',
            'type'    => 'textarea',
            'default' => '{name}, your online consultation request for {date} at {time} has been captured. The Aaroh Care team will review the request and confirm the appointment.',
        ],
        'form_name_label' => [
            'section' => 'aaroh_form',
            'label'   => 'Name label',
            'type'    => 'text',
            'default' => 'Full name',
        ],
        'form_name_placeholder' => [
            'section' => 'aaroh_form',
            'label'   => 'Name placeholder',
            'type'    => 'text',
            'default' => 'Enter patient name',
        ],
        'form_name_error' => [
            'section' => 'aaroh_form',
            'label'   => 'Name error',
            'type'    => 'text',
            'default' => 'Enter the patient name.',
        ],
        'form_phone_label' => [
            'section' => 'aaroh_form',
            'label'   => 'Phone label',
            'type'    => 'text',
            'default' => 'Contact number',
        ],
        'form_phone_placeholder' => [
            'section' => 'aaroh_form',
            'label'   => 'Phone placeholder',
            'type'    => 'text',
            'default' => 'Enter contact number',
        ],
        'form_phone_error' => [
            'section' => 'aaroh_form',
            'label'   => 'Phone error',
            'type'    => 'text',
            'default' => 'Enter a valid contact number.',
        ],
        'form_email_label' => [
            'section' => 'aaroh_form',
            'label'   => 'Email label',
            'type'    => 'text',
            'default' => 'Email address',
        ],
        'form_email_placeholder' => [
            'section' => 'aaroh_form',
            'label'   => 'Email placeholder',
            'type'    => 'text',
            'default' => 'name@example.com',
        ],
        'form_email_error' => [
            'section' => 'aaroh_form',
            'label'   => 'Email error',
            'type'    => 'text',
            'default' => 'Enter a valid email address.',
        ],
        'form_issue_label' => [
            'section' => 'aaroh_form',
            'label'   => 'Health issue label',
            'type'    => 'text',
            'default' => 'Health issue',
        ],
        'form_issue_placeholder' => [
            'section' => 'aaroh_form',
            'label'   => 'Health issue placeholder',
            'type'    => 'textarea',
            'default' => 'Describe symptoms, concerns, or goals for the consultation',
        ],
        'form_issue_error' => [
            'section' => 'aaroh_form',
            'label'   => 'Health issue error',
            'type'    => 'text',
            'default' => 'Describe the health issue for the appointment request.',
        ],
        'form_date_label' => [
            'section' => 'aaroh_form',
            'label'   => 'Date label',
            'type'    => 'text',
            'default' => 'Preferred date',
        ],
        'form_date_error' => [
            'section' => 'aaroh_form',
            'label'   => 'Date error',
            'type'    => 'text',
            'default' => 'Select a preferred appointment date.',
        ],
        'form_time_label' => [
            'section' => 'aaroh_form',
            'label'   => 'Time label',
            'type'    => 'text',
            'default' => 'Preferred time',
        ],
        'form_time_placeholder' => [
            'section' => 'aaroh_form',
            'label'   => 'Time placeholder',
            'type'    => 'text',
            'default' => 'Select a time slot',
        ],
        'form_time_error' => [
            'section' => 'aaroh_form',
            'label'   => 'Time error',
            'type'    => 'text',
            'default' => 'Choose a preferred time slot.',
        ],
        'form_time_slots' => [
            'section' => 'aaroh_form',
            'label'   => 'Time slots (one per line)',
            'type'    => 'textarea',
            'default' => "04:00 PM\n05:00 PM\n06:00 PM\n07:00 PM",
        ],
        'faq_eyebrow' => [
            'section' => 'aaroh_faq_head',
            'label'   => 'Eyebrow',
            'type'    => 'text',
            'default' => 'FAQ',
        ],
        'faq_title' => [
            'section' => 'aaroh_faq_head',
            'label'   => 'Title',
            'type'    => 'textarea',
            'default' => 'Questions patients often ask before booking.',
        ],
        'articles_eyebrow' => [
            'section' => 'aaroh_articles_head',
            'label'   => 'Eyebrow',
            'type'    => 'text',
            'default' => 'Journal',
        ],
        'articles_title' => [
            'section' => 'aaroh_articles_head',
            'label'   => 'Title',
            'type'    => 'textarea',
            'default' => 'Articles on homoeopathic care and holistic wellbeing.',
        ],
        'articles_intro' => [
            'section' => 'aaroh_articles_head',
            'label'   => 'Intro',
            'type'    => 'textarea',
            'default' => 'Read recent notes from Aaroh Care on consultation focus, everyday health, and natural healing.',
        ],
        'footer_copy' => [
            'section' => 'aaroh_footer',
            'label'   => 'Copyright line',
            'type'    => 'text',
            'default' => '© 2026 AAROH CARE - HOMOEOPATHY. Natural Healing. Holistic Wellbeing.',
        ],
        'footer_link' => [
            'section' => 'aaroh_footer',
            'label'   => 'Footer link text',
            'type'    => 'text',
            'default' => 'Book your consultation',
        ],
    ];
}
